version: 0.1
log:
      fields:
         service: registry
storage:
      filesystem:
         rootdirectory: /var/lib/registry
http:
      addr: :5000
      tls:
         certificate: "/certs/domain.crt"
         key: "/certs/domain.key"
auth:
      token:
         realm: "https://dregistry.stormclouds.me:5001/auth"
         service: "Docker registry"
         issuer: "Docker Registry Auth Server"
         rootcertbundle: "/certs/fullchain.crt"
